# Generated by Django 2.2.4 on 2020-01-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField(max_length=2000)),
                ('customer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_money', models.BigIntegerField(blank=True, default=0, null=True)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='customer/displaypic')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('item_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='items/displaypic')),
                ('item_status', models.CharField(choices=[('Available', 'Available'), ('Out Of Stock', 'Out Of Stock')], max_length=200)),
                ('item_quantity', models.PositiveIntegerField(default=0)),
                ('item_sales', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['item_sales'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_address', models.CharField(blank=True, max_length=300, null=True)),
                ('vendor_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('vendor_email', models.EmailField(blank=True, max_length=300, null=True)),
                ('vendor_image', models.ImageField(blank=True, null=True, upload_to='vendor/displaypic')),
                ('vendor_money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('In Cart', 'In Cart'), ('Order Placed', 'Order Placed'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='In Cart', max_length=200)),
                ('item_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Item')),
                ('order_customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Customer')),
                ('order_vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Vendor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_wishlist',
            field=models.ManyToManyField(related_name='myWishlist', to='ecommerce.Item'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_created_date', models.DateField(auto_now=True)),
                ('cart_created_time', models.TimeField(auto_now=True)),
                ('cart_ordered', models.CharField(choices=[('Ordered', 'Ordered'), ('Not Ordered', 'Not Ordered')], default='Not Ordered', max_length=20)),
                ('cart_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Customer')),
                ('my_cart', models.ManyToManyField(related_name='myCart', to='ecommerce.Order')),
            ],
        ),
    ]
